language: c

env:
  - LUA="Lua 5.1"
  - LUA="Lua 5.2"
  - LUA="LuaJIT 2.0"

before_install:
  - bash .travis_setup.sh

install:
  - sudo luarocks make
  - sudo luarocks install busted

script: busted spec

branches:
  only:
    - master

notifications:
  webhooks:
    - http://hollow-mountain-1250.herokuapp.com/hubot/travis
  recipients:
    - engineers@olivinelabs.com
  email:
    on_success: always
    on_failure: always
